"""Add EvaluationMetadata model

Revision ID: 4836c4e6fee0
Revises: c4c2d5e9284d
Create Date: 2026-07-01 00:14:55.910050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4836c4e6fee0'
down_revision: Union[str, None] = 'c4c2d5e9284d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('domain_id', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('normalized_question', sa.String(), nullable=True),
    sa.Column('retrieval_path', sa.String(), nullable=True),
    sa.Column('retrieved_sources', sa.Integer(), nullable=True),
    sa.Column('prompt_length', sa.Integer(), nullable=True),
    sa.Column('completion_length', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('confidence_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_metadata_domain_id'), 'evaluation_metadata', ['domain_id'], unique=False)
    op.create_index(op.f('ix_evaluation_metadata_session_id'), 'evaluation_metadata', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_metadata_session_id'), table_name='evaluation_metadata')
    op.drop_index(op.f('ix_evaluation_metadata_domain_id'), table_name='evaluation_metadata')
    op.drop_table('evaluation_metadata')
    # ### end Alembic commands ###
