"""Add widget_key to Domain and session_id to Lead

Revision ID: 70510ee7c412
Revises: ee4139359631
Create Date: 2026-06-22 18:13:03.894645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70510ee7c412'
down_revision: Union[str, None] = 'ee4139359631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('widget_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_domains_widget_key'), 'domains', ['widget_key'], unique=True)
    op.add_column('leads', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'session_id')
    op.drop_index(op.f('ix_domains_widget_key'), table_name='domains')
    op.drop_column('domains', 'widget_key')
    # ### end Alembic commands ###
