"""add aliases

Revision ID: 7f421add2960
Revises: 381c9b64797c
Create Date: 2026-06-23 16:34:59.173309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f421add2960'
down_revision: Union[str, None] = '381c9b64797c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_questions', sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_questions', 'aliases')
    # ### end Alembic commands ###
