"""add display_order to faq_questions

Revision ID: bf573ad97587
Revises: d60e1269f9df
Create Date: 2026-06-30 17:44:26.713110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf573ad97587'
down_revision: Union[str, None] = 'd60e1269f9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_questions', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_questions', 'display_order')
    # ### end Alembic commands ###
