"""add is_active to document_source

Revision ID: c0f79cdfa1af
Revises: 22e4497ecb4f
Create Date: 2026-07-01 22:29:13.207956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f79cdfa1af'
down_revision: Union[str, None] = '22e4497ecb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_sources', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_sources', 'is_active')
    # ### end Alembic commands ###
