"""Add required indexes

Revision ID: c3eb7cbde4f6
Revises: 7ebe469c5c66
Create Date: 2026-06-23 11:13:43.992248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3eb7cbde4f6'
down_revision: Union[str, None] = '7ebe469c5c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_session_id_created_at', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_session_id_sender', 'chat_messages', ['session_id', 'sender'], unique=False)
    op.create_index(op.f('ix_chat_sessions_domain_id'), 'chat_sessions', ['domain_id'], unique=False)
    op.create_index('ix_chat_sessions_domain_id_status', 'chat_sessions', ['domain_id', 'status', sa.text('last_message_at DESC')], unique=False)
    op.create_index('ix_chat_sessions_open_unread', 'chat_sessions', ['domain_id', 'unread_admin'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_index(op.f('ix_domain_categories_domain_id'), 'domain_categories', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domains_organization_id'), 'domains', ['organization_id'], unique=False)
    op.create_index(op.f('ix_failed_questions_domain_id'), 'failed_questions', ['domain_id'], unique=False)
    op.create_index('ix_failed_questions_domain_id_is_spam', 'failed_questions', ['domain_id', 'is_spam', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_failed_questions_spam', 'failed_questions', ['domain_id', sa.text('spam_count DESC')], unique=False, postgresql_where=sa.text('is_spam = true'))
    op.create_index('ix_faq_categories_active_org', 'faq_categories', ['organization_id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_faq_categories_organization_id'), 'faq_categories', ['organization_id'], unique=False)
    op.create_index('ix_faq_questions_active_faq_id', 'faq_questions', ['faq_id', sa.text('created_at DESC')], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_faq_questions_faq_id'), 'faq_questions', ['faq_id'], unique=False)
    op.create_index('ix_faq_questions_faq_id_status', 'faq_questions', ['faq_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_domain_id'), 'leads', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_domain_id'), table_name='leads')
    op.drop_index('ix_faq_questions_faq_id_status', table_name='faq_questions')
    op.drop_index(op.f('ix_faq_questions_faq_id'), table_name='faq_questions')
    op.drop_index('ix_faq_questions_active_faq_id', table_name='faq_questions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_faq_categories_organization_id'), table_name='faq_categories')
    op.drop_index('ix_faq_categories_active_org', table_name='faq_categories', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_failed_questions_spam', table_name='failed_questions', postgresql_where=sa.text('is_spam = true'))
    op.drop_index('ix_failed_questions_domain_id_is_spam', table_name='failed_questions')
    op.drop_index(op.f('ix_failed_questions_domain_id'), table_name='failed_questions')
    op.drop_index(op.f('ix_domains_organization_id'), table_name='domains')
    op.drop_index(op.f('ix_domain_categories_domain_id'), table_name='domain_categories')
    op.drop_index('ix_chat_sessions_open_unread', table_name='chat_sessions', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_chat_sessions_domain_id_status', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_domain_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_messages_session_id_sender', table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_id_created_at', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    # ### end Alembic commands ###
