"""update index for display_order

Revision ID: c4c2d5e9284d
Revises: bf573ad97587
Create Date: 2026-06-30 17:53:16.179707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c2d5e9284d'
down_revision: Union[str, None] = 'bf573ad97587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faq_questions_active_faq_id', table_name='faq_questions', postgresql_where="((status)::text = 'active'::text)")
    op.create_index('ix_faq_questions_active_faq_id', 'faq_questions', ['faq_id', sa.text('display_order ASC'), sa.text('created_at DESC')], unique=False, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faq_questions_active_faq_id', table_name='faq_questions', postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_faq_questions_active_faq_id', 'faq_questions', ['faq_id', sa.text('created_at DESC')], unique=False, postgresql_where="((status)::text = 'active'::text)")
    # ### end Alembic commands ###
