"""add error_stage to document_sources

Revision ID: d552605a6a92
Revises: a1b2c3d4e5f6
Create Date: 2026-06-29 13:09:32.731838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd552605a6a92'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_sources', sa.Column('error_stage', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_sources_domain_id'), 'document_sources', ['domain_id'], unique=False)
    op.create_index(op.f('ix_document_sources_organization_id'), 'document_sources', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_sources_organization_id'), table_name='document_sources')
    op.drop_index(op.f('ix_document_sources_domain_id'), table_name='document_sources')
    op.drop_column('document_sources', 'error_stage')
    # ### end Alembic commands ###
