"""Add cascade delete to domain foreign keys

Revision ID: d60e1269f9df
Revises: d552605a6a92
Create Date: 2026-06-30 16:35:47.099892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60e1269f9df'
down_revision: Union[str, None] = 'd552605a6a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chat_sessions_domain_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('document_sources_domain_id_fkey', 'document_sources', type_='foreignkey')
    op.create_foreign_key(None, 'document_sources', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('domain_categories_domain_id_fkey', 'domain_categories', type_='foreignkey')
    op.create_foreign_key(None, 'domain_categories', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('failed_questions_domain_id_fkey', 'failed_questions', type_='foreignkey')
    op.create_foreign_key(None, 'failed_questions', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('faqs_domain_id_fkey', 'faqs', type_='foreignkey')
    op.create_foreign_key(None, 'faqs', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('leads_domain_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('retraining_jobs_domain_id_fkey', 'retraining_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'retraining_jobs', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retraining_jobs', type_='foreignkey')
    op.create_foreign_key('retraining_jobs_domain_id_fkey', 'retraining_jobs', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_domain_id_fkey', 'leads', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.create_foreign_key('faqs_domain_id_fkey', 'faqs', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'failed_questions', type_='foreignkey')
    op.create_foreign_key('failed_questions_domain_id_fkey', 'failed_questions', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'domain_categories', type_='foreignkey')
    op.create_foreign_key('domain_categories_domain_id_fkey', 'domain_categories', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'document_sources', type_='foreignkey')
    op.create_foreign_key('document_sources_domain_id_fkey', 'document_sources', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_domain_id_fkey', 'chat_sessions', 'domains', ['domain_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
