"""Add FailedQuestion and resolution_type

Revision ID: ee4139359631
Revises: 2caa40570322
Create Date: 2026-06-22 17:46:10.687872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4139359631'
down_revision: Union[str, None] = '2caa40570322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('ai_response', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('spam_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_sessions', sa.Column('resolution_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'resolution_type')
    op.drop_table('failed_questions')
    # ### end Alembic commands ###
